{"name": "test_editorial_system_end_user[chrome-Divya Balasubramanya-1WTC NY-Hari Sreekumaran-High-K4-Access-None-None-None-Sum test-Desc test]", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <Pages.EditorialSystemEndUser.EditorialSystemModuleEndUser object at 0x7fac427f4760>, caller = 'Divya Balasubramanya', office = '1WTC NY', affected_user = 'Hari Sreekumaran', urgency = 'High'\neditorial_platform = 'K4', issue_type = 'Access', device = None, operating_system = None, browser = None, summary = 'Sum test', description = 'Desc test'\n\n    def fill_editorial_systems_module_end_user(self, caller,office, affected_user, urgency,editorial_platform, issue_type , device, operating_system, browser,summary,description):\n        try:\n            self.click(Locators.SEARCH_TEXTBOX_MODULE_END_USER)\n            self.enter_text(Locators.SEARCH_TEXTBOX_MODULE_END_USER, \"Editorial Systems Incident\")\n            time.sleep(3)\n            self.send_enter(Locators.SEARCH_TEXTBOX_MODULE_END_USER)\n            time.sleep(2)\n            self.click(Locators.EDITORIAL_SYSTEMS_CLICK)\n    \n            self.is_visible(Locators.EDITORIAL_SYSTEMS_TITLE)\n    \n            time.sleep(3)\n    \n            self.fill_caller(caller)\n            self.fill_office(office)\n            self.fill_affected_user(affected_user)\n>           self.choose_urgency(urgency)\n\nPages/EditorialSystemEndUser.py:139: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Pages.EditorialSystemEndUser.EditorialSystemModuleEndUser object at 0x7fac427f4760>, urgency = 'High'\n\n    def choose_urgency(self, urgency):\n        if urgency == \"\":\n            pass\n        else:\n            self.click(Locators.URGENCY_EDITORIAL_SYSTEMS)\n            time.sleep(2)\n            self.click(Locators.URGENCY_EDITORIAL_SYSTEMS_TEXTBOX)\n            time.sleep(2)\n>           self.enter_text(Locators.URGENCY_EDITORIAL_SYSTEMS_TEXTBOX, )\nE           TypeError: enter_text() missing 1 required positional argument: 'text'\n\nPages/EditorialSystemEndUser.py:57: TypeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <TestCases.test_editorial_systems_end_user.TestEditorialSystemEndUser object at 0x7fac427a6220>, caller = 'Divya Balasubramanya', office = '1WTC NY', affected_user = 'Hari Sreekumaran', urgency = 'High'\neditorial_platform = 'K4', issue_type = 'Access', device = None, operating_system = None, browser = None, summary = 'Sum test', description = 'Desc test'\n\n    @pytest.mark.parametrize('caller,office, affected_user, urgency,editorial_platform, issue_type , device, operating_system, browser,summary, description',\n                             read_data(\"Editorial Systems Incident\"))\n    def test_editorial_system_end_user(self, caller,office, affected_user, urgency,editorial_platform, issue_type , device, operating_system, browser,summary, description):\n        print(\"inside\")\n        self.driver.get(\"https://supporttest.condenastint.com/sp\")\n        time.sleep(3)\n        login_cred_obj = LoginCred(self.driver)\n        login_cred_obj.login_cred()\n        time.sleep(40)\n        self.editorial_system_end_user_obj = EditorialSystemModuleEndUser(self.driver)\n>       self.editorial_system_end_user_obj.fill_editorial_systems_module_end_user(caller,office, affected_user, urgency,editorial_platform, issue_type , device, operating_system, browser,summary,description)\n\nTestCases/test_editorial_systems_end_user.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Pages.EditorialSystemEndUser.EditorialSystemModuleEndUser object at 0x7fac427f4760>, caller = 'Divya Balasubramanya', office = '1WTC NY', affected_user = 'Hari Sreekumaran', urgency = 'High'\neditorial_platform = 'K4', issue_type = 'Access', device = None, operating_system = None, browser = None, summary = 'Sum test', description = 'Desc test'\n\n    def fill_editorial_systems_module_end_user(self, caller,office, affected_user, urgency,editorial_platform, issue_type , device, operating_system, browser,summary,description):\n        try:\n            self.click(Locators.SEARCH_TEXTBOX_MODULE_END_USER)\n            self.enter_text(Locators.SEARCH_TEXTBOX_MODULE_END_USER, \"Editorial Systems Incident\")\n            time.sleep(3)\n            self.send_enter(Locators.SEARCH_TEXTBOX_MODULE_END_USER)\n            time.sleep(2)\n            self.click(Locators.EDITORIAL_SYSTEMS_CLICK)\n    \n            self.is_visible(Locators.EDITORIAL_SYSTEMS_TITLE)\n    \n            time.sleep(3)\n    \n            self.fill_caller(caller)\n            self.fill_office(office)\n            self.fill_affected_user(affected_user)\n            self.choose_urgency(urgency)\n            self.fill_editorial_platform(editorial_platform)\n            self.fill_issue_type(issue_type)\n            self.fill_device(device)\n    \n            self.fill_operating_system(operating_system)\n            self.fill_browser(browser)\n            self.fill_summary(summary)\n            self.fill_description(description)\n            self.click_submit()\n    \n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Editorial System \",attachment_type=AttachmentType.PNG)\n    \n        except:\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Editorial System \",\n                          attachment_type=AttachmentType.PNG)\n>           assert False\nE           AssertionError\n\nPages/EditorialSystemEndUser.py:155: AssertionError"}, "attachments": [{"name": "Editorial System ", "source": "4f493170-7a0c-433d-b744-000a3052a072-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "31b5caa9-bf5b-404c-9549-382683341f19-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "init_driver", "value": "'chrome'"}, {"name": "caller", "value": "'Divya Balasubramanya'"}, {"name": "office", "value": "'1WTC NY'"}, {"name": "affected_user", "value": "'Hari Sreekumaran'"}, {"name": "urgency", "value": "'High'"}, {"name": "editorial_platform", "value": "'K4'"}, {"name": "issue_type", "value": "'Access'"}, {"name": "device", "value": "None"}, {"name": "operating_system", "value": "None"}, {"name": "browser", "value": "None"}, {"name": "summary", "value": "'Sum test'"}, {"name": "description", "value": "'Desc test'"}], "start": 1639387406539, "stop": 1639387550516, "uuid": "c5a39109-5f6c-4f16-a025-26670323ac82", "historyId": "5c164d479082b66575b32dbf989dfadc", "testCaseId": "ee07c1e7b59b622f86a7723636380e16", "fullName": "TestCases.test_editorial_systems_end_user.TestEditorialSystemEndUser#test_editorial_system_end_user", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_editorial_systems_end_user"}, {"name": "subSuite", "value": "TestEditorialSystemEndUser"}, {"name": "host", "value": "X7E062921133115"}, {"name": "thread", "value": "75375-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_editorial_systems_end_user"}]}